[package]
name = "relaxed"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/dimpolo/relaxed/"

[dependencies]
atomic_float = { version = "0.1.0", default_features = false }